# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Minecraft Properties
minecraft_version = 1.21.11
minecraft_version_supported = [1.21.11]
minecraft_version_filter = releases
minecraft_version_lower = 1.21.10
minecraft_version_upper = 1.22.0

# File Name
minecraft_version_name = 1.21.11
archives_base_name = MoreFrameVariants

# Mod Properties
mod_id = mstv-mframev
mod_name = More (Item/Painting) Frame Variants (MStV+)
mod_name_short = More Frame Variants
mod_description = This mod adds more variants of Item and Painting Frames.
mod_version = 1.2.6
mod_license = CC-BY-NC-SA-4.0
maven_group = de.pnku

# Dependencies
mstv_version = 1.4.14
mstv_version_id = SctdPd3L
fif_version_id = 4QQcgJi6
fc_api_version_id = uXrWPsCu
puzzles_lib_version_id = owXZpJai