# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Fabric Properties
minecraft_version = 1.21.5-rc2
loader_version = 0.16.10
fapi_version = 0.119.3+1.21.5

# Mod Properties
mod_id = mstv-mframev
mod_name = More (Item/Painting) Frame Variants (MStV+)
mod_description = This mod adds more variants of Item and Painting Frames.
mod_version = 1.1.2
mod_license = MIT
maven_group = de.pnku
archives_base_name = MoreFrameVariants

# Dependencies
mstv_version = 1.4.2
mstv_version_id = P2QjtOJF